### ISSUE TITLE
emg

### ISSUE THREAD

**Issue by vega2730** [rehmanali1994/LabVIEW-Interface-for-Olimex-ECG-EMG-Arduino-Shield#1]
thank you .it really works great for ecg , but when i change the delay time to use it around 1000 hz it doen't work ,what can i do ?

**Comment by rehmanali1994** [comment]
See the following two lines from the Arduino sketch:
`#define SAMPFREQ 256                      // ADC sampling rate 256`
`#define TIMER2VAL (1024/(SAMPFREQ)) // Set 256Hz sampling frequency`
I think you need to modify both the LabVIEW vi file and the Arduino sketch to get this to work at different frequencies. Also I would pick frequencies that produce integer values for TIMER2VAL so something like 1024 for the SAMPFREQ should work.

**Comment by vega2730** [comment]
yes,you are right and since the arduino seems to be able to sample 6 channels in 4 ms ,  TIMER2VAL frequency has to change too.
